default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS", 5) %>
  host: <%= ENV["PGHOST"] || "localhost" %>
  port: <%= ENV["PGPORT"] || 5432 %>
  username: <%= ENV["PGUSER"] || ENV["USER"] %>
  password: <%= ENV["PGPASSWORD"] %>

development:
  <<: *default
  database: vote_sa_poli_backend_development

test:
  <<: *default
  database: vote_sa_poli_backend_test

production:
  <<: *default
  url: <%= ENV['DATABASE_URL'] %>
